name: DataOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga el código del repositorio en el servidor de GitHub
    - name: Copiar repositorio
      uses: actions/checkout@v4

    # 2. Configura la versión correcta de Python
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # 3. Instala Poetry de forma global en el contenedor de GitHub
    - name: Instalar Poetry
      run: |
        pip install poetry

    # 4. Instala las dependencias exactas usando el archivo poetry.lock
    - name: Instalar dependencias
      run: |
        poetry install

    # 5. Ejecuta la suite de pruebas automatizadas (Pytest)
    - name: Ejecutar Pruebas Automatizadas
      run: |
        poetry run pytest